"""
District Award Travel — One-Time Setup Script
Run this ONCE to configure everything. You never touch it again.

Usage: python setup.py
"""

import os
import subprocess
import sys
import json
from pathlib import Path

BASE_DIR = Path(__file__).parent
GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
CYAN = "\033[96m"
BOLD = "\033[1m"
RESET = "\033[0m"


def section(title):
    print(f"\n{BOLD}{CYAN}{'─' * 50}")
    print(f"  {title}")
    print(f"{'─' * 50}{RESET}")


def ok(msg): print(f"  {GREEN}✓ {msg}{RESET}")
def warn(msg): print(f"  {YELLOW}⚠ {msg}{RESET}")
def err(msg): print(f"  {RED}✗ {msg}{RESET}")
def ask(prompt): return input(f"  {CYAN}▸ {prompt}{RESET} ").strip()


def check_python():
    section("Checking Python")
    version = sys.version_info
    if version.major >= 3 and version.minor >= 9:
        ok(f"Python {version.major}.{version.minor}.{version.micro}")
    else:
        err(f"Python 3.9+ required. Found: {version.major}.{version.minor}")
        sys.exit(1)


def check_node():
    section("Checking Node.js")
    try:
        result = subprocess.run(["node", "--version"], capture_output=True, text=True)
        ok(f"Node.js {result.stdout.strip()}")
    except FileNotFoundError:
        warn("Node.js not found. Jordan's browser automation will be unavailable.")
        warn("Install from: https://nodejs.org")


def check_git():
    section("Checking Git")
    try:
        result = subprocess.run(["git", "--version"], capture_output=True, text=True)
        ok(result.stdout.strip())
    except FileNotFoundError:
        err("Git not found. Install from: https://git-scm.com")
        sys.exit(1)


def check_claude():
    section("Checking Claude Code CLI")
    try:
        result = subprocess.run(["claude", "--version"], capture_output=True, text=True)
        ok(f"Claude Code {result.stdout.strip()}")
        return True
    except FileNotFoundError:
        warn("Claude Code CLI not found.")
        warn("The engineers run via Claude Code. Install it:")
        warn("  npm install -g @anthropic-ai/claude-code")
        warn("  Then run: claude login")
        return False


def setup_env():
    section("Environment Configuration")
    env_file = BASE_DIR / ".env"

    if env_file.exists():
        warn(".env already exists — skipping. Edit manually if needed.")
        return

    print(f"\n  {YELLOW}Enter your credentials below.")
    print(f"  These are stored locally in .env and never shared.{RESET}\n")

    github_token = ask("GitHub Personal Access Token (for auto-commits): ")
    github_repo = ask("GitHub repo (e.g. username/district-award-travel): ")
    email_addr = ask("Your email address (for morning briefing reports): ")
    email_smtp = ask("SMTP server (e.g. smtp.gmail.com) [press Enter to skip]: ")
    email_pass = ask("Email password / app password [press Enter to skip]: ") if email_smtp else ""

    # Airline credentials (optional — used by Jordan's browser automation)
    print(f"\n  {YELLOW}Airline credentials (optional — for browser automation):{RESET}")
    ana_user = ask("ANA Mileage Club username [Enter to skip]: ")
    ana_pass = ask("ANA Mileage Club password [Enter to skip]: ") if ana_user else ""

    env_content = f"""# District Award Travel — Environment Configuration
# Generated by setup.py — edit as needed

# ── GitHub ──────────────────────────────────────────────────
GITHUB_TOKEN={github_token}
GITHUB_REPO={github_repo}

# ── Email Reports ────────────────────────────────────────────
REPORT_EMAIL={email_addr}
SMTP_SERVER={email_smtp}
SMTP_PORT=587
SMTP_USERNAME={email_addr}
SMTP_PASSWORD={email_pass}

# ── Airline Credentials ──────────────────────────────────────
ANA_USERNAME={ana_user}
ANA_PASSWORD={ana_pass}

# ── Booking Safety ───────────────────────────────────────────
# Set to 'true' ONLY when you want agents to actually book
BOOKING_ENABLED=false

# ── Platform ─────────────────────────────────────────────────
API_HOST=localhost
API_PORT=8000
DATABASE_URL=sqlite:///./platform/district_award_travel.db
"""

    env_file.write_text(env_content)
    ok(f".env created at {env_file}")


def setup_git_repo():
    section("Git Repository Setup")

    git_dir = BASE_DIR / ".git"
    if git_dir.exists():
        ok("Git repo already initialized")
    else:
        subprocess.run(["git", "init"], cwd=BASE_DIR, capture_output=True)
        ok("Git repo initialized")

    # Read GitHub repo from .env
    env_file = BASE_DIR / ".env"
    github_repo = ""
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            if line.startswith("GITHUB_REPO="):
                github_repo = line.split("=", 1)[1].strip()

    if github_repo:
        result = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            cwd=BASE_DIR, capture_output=True, text=True
        )
        if result.returncode != 0:
            subprocess.run(
                ["git", "remote", "add", "origin", f"https://github.com/{github_repo}.git"],
                cwd=BASE_DIR, capture_output=True
            )
            ok(f"Remote set: https://github.com/{github_repo}")
        else:
            ok(f"Remote already set: {result.stdout.strip()}")

    # Create .gitignore
    gitignore = BASE_DIR / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(""".env
__pycache__/
*.pyc
node_modules/
.tmp_prompt_*
*.db
logs/
""")
        ok(".gitignore created")


def install_python_deps():
    section("Installing Python Dependencies")
    req_file = BASE_DIR / "requirements.txt"

    if not req_file.exists():
        req_file.write_text("""fastapi>=0.110.0
uvicorn[standard]>=0.29.0
sqlalchemy>=2.0.0
pydantic>=2.0.0
python-dotenv>=1.0.0
requests>=2.31.0
beautifulsoup4>=4.12.0
celery>=5.3.0
redis>=5.0.0
jinja2>=3.1.0
aiofiles>=23.0.0
httpx>=0.27.0
""")
        ok("requirements.txt created")

    print(f"  Installing packages...")
    result = subprocess.run(
        [sys.executable, "-m", "pip", "install", "-r", str(req_file), "-q"],
        capture_output=True, text=True
    )
    if result.returncode == 0:
        ok("Python packages installed")
    else:
        warn(f"Some packages failed: {result.stderr[:200]}")


def install_node_deps():
    section("Installing Node.js Dependencies")
    pkg_file = BASE_DIR / "package.json"

    if not pkg_file.exists():
        pkg_content = {
            "name": "district-award-travel",
            "version": "1.0.0",
            "description": "District Award Travel — Browser Automation Layer",
            "main": "platform/src/automation/ana_login.js",
            "scripts": {
                "ana": "node platform/src/automation/ana_login.js",
                "transfers": "node platform/src/automation/transfer_monitor.js",
                "test": "node --experimental-vm-modules node_modules/.bin/jest"
            },
            "dependencies": {
                "playwright": "^1.44.0",
                "playwright-extra": "^4.3.6",
                "puppeteer-extra-plugin-stealth": "^2.11.2",
                "axios": "^1.7.0",
                "cheerio": "^1.0.0",
                "dotenv": "^16.4.0",
                "winston": "^3.13.0"
            }
        }
        with open(pkg_file, "w") as f:
            json.dump(pkg_content, f, indent=2)
        ok("package.json created")

    try:
        result = subprocess.run(
            ["npm", "install", "--silent"],
            cwd=BASE_DIR, capture_output=True, text=True
        )
        if result.returncode == 0:
            ok("Node packages installed")
            # Install Playwright browsers
            subprocess.run(
                ["npx", "playwright", "install", "chromium"],
                cwd=BASE_DIR, capture_output=True
            )
            ok("Playwright Chromium browser installed")
        else:
            warn("npm install failed — check Node.js installation")
    except FileNotFoundError:
        warn("npm not found — skipping Node.js setup")


def schedule_nightly_run():
    section("Scheduling Nightly Engineering Run")

    if sys.platform == "win32":
        # Windows Task Scheduler
        task_xml = f"""<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <Triggers>
    <CalendarTrigger>
      <StartBoundary>2026-01-01T02:00:00</StartBoundary>
      <ScheduleByDay><DaysInterval>1</DaysInterval></ScheduleByDay>
    </CalendarTrigger>
  </Triggers>
  <Actions>
    <Exec>
      <Command>{sys.executable}</Command>
      <Arguments>{BASE_DIR / 'orchestrator.py'}</Arguments>
      <WorkingDirectory>{BASE_DIR}</WorkingDirectory>
    </Exec>
  </Actions>
  <Settings>
    <ExecutionTimeLimit>PT4H</ExecutionTimeLimit>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
  </Settings>
</Task>"""

        task_file = BASE_DIR / "nightly_task.xml"
        task_file.write_text(task_xml)

        result = subprocess.run(
            ["schtasks", "/Create", "/TN", "DistrictAwardTravel_Nightly",
             "/XML", str(task_file), "/F"],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            ok("Windows Task Scheduler: Engineers run nightly at 2:00 AM")
        else:
            warn(f"Could not auto-schedule. Run manually: python orchestrator.py")
            warn(f"Or open Task Scheduler and import: {task_file}")
    else:
        warn("Non-Windows: Add to crontab manually:")
        warn(f"  0 2 * * * {sys.executable} {BASE_DIR}/orchestrator.py")


def print_summary():
    section("Setup Complete")
    print(f"""
{GREEN}{BOLD}  District Award Travel is ready.{RESET}

  {CYAN}What happens next:{RESET}
  1. Every night at 2:00 AM, the orchestrator wakes up
  2. Marcus, Jordan, and Priya each pick their assigned tasks
  3. They write real code and commit it to your GitHub repo
  4. You wake up to a morning brief in logs/morning_brief_{{date}}.txt

  {CYAN}To run the engineers right now:{RESET}
    python orchestrator.py

  {CYAN}To run a single engineer:{RESET}
    python orchestrator.py --engineer marcus
    python orchestrator.py --engineer jordan
    python orchestrator.py --engineer priya

  {CYAN}To preview tasks without executing:{RESET}
    python orchestrator.py --dry-run

  {CYAN}To add new tasks for the engineers:{RESET}
    Edit tasks/backlog.json — add to the "backlog" array

  {YELLOW}IMPORTANT: Set BOOKING_ENABLED=true in .env ONLY when{RESET}
  {YELLOW}you are ready for agents to make real bookings.{RESET}

  {GREEN}Engineers active: Marcus Webb · Jordan Reyes · Priya Kapoor{RESET}
""")


if __name__ == "__main__":
    print(f"\n{BOLD}{CYAN}")
    print("  DISTRICT AWARD TRAVEL — Setup Wizard")
    print(f"  {RESET}")

    check_python()
    check_node()
    check_git()
    check_claude()
    setup_env()
    setup_git_repo()
    install_python_deps()
    install_node_deps()
    schedule_nightly_run()
    print_summary()
