apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: https://localhost:6443
    name: kubernetes
contexts:
  - context:
      cluster: kubernetes
    name: kubernetes
users:
  - name: kubernetes
    user:
      client-certificate: /etc/kubernetes/pki/admin.crt
      client-key: /etc/kubernetes/pki/admin.key
current-context: kubernetes
