version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - app
    restart: always

  app:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=dat
      - POSTGRES_PASSWORD=dat
      - POSTGRES_DB=dat
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  ml:
    build: ./ml
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - app
    restart: always

volumes:
  db-data:
