apiVersion: v1
kind: Service
metadata:
  name: monitoring
spec:
  selector:
    app: monitoring
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
      - name: monitoring
        image: prometheus/prometheus:v2.34.0
        ports:
        - containerPort: 9090
