http {
    server {
        listen 80;
        server_name example.com;

        location / {
            proxy_pass http://dashboard:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /data-visualization {
            proxy_pass http://data-visualization:5001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
